services:
  movewiz-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: stack.env
    ports:
      - '3033:3000'
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - $PWD:/app

  db:
    image: mariadb:11
    restart: always
    environment:
      - MARIADB_USER=user
      - MARIADB_PASSWORD=mypswd
      - MARIADB_DATABASE=my_db
      - MARIADB_ROOT_PASSWORD=rootpswd
    volumes:
      - mariadb_data:/var/lib/mysql/
    healthcheck:
      test: ["CMD-SHELL", "mariadb -uroot -prootpswd -e 'use my_db;'"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mariadb_data:
